2022/04/09 10:21:00 [error] 27#27: *2 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.24.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "localhost"
2022/04/10 13:24:41 [emerg] 1#1: host not found in upstream "php-fpm" in /etc/nginx/nginx.conf:33
2022/04/10 13:25:09 [emerg] 1#1: host not found in upstream "php-fpm" in /etc/nginx/nginx.conf:33
2022/04/10 13:26:38 [emerg] 1#1: host not found in upstream "php-fpm" in /etc/nginx/nginx.conf:33
2022/04/10 21:42:25 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.80.2:9000", host: "localhost", referrer: "https://medium.com/@dam1enWeb/symfony-5-2-et-php-8-sous-docker-en-5-minutes-942ca6e94ce0"
2022/04/10 21:42:28 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.80.2:9000", host: "localhost", referrer: "https://medium.com/@dam1enWeb/symfony-5-2-et-php-8-sous-docker-en-5-minutes-942ca6e94ce0"
2022/04/10 21:42:29 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.80.2:9000", host: "localhost", referrer: "https://medium.com/@dam1enWeb/symfony-5-2-et-php-8-sous-docker-en-5-minutes-942ca6e94ce0"
2022/04/10 21:44:15 [error] 25#25: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET /fr HTTP/1.1", upstream: "fastcgi://192.168.80.3:9000", host: "localhost", referrer: "https://medium.com/@dam1enWeb/symfony-5-2-et-php-8-sous-docker-en-5-minutes-942ca6e94ce0"
2022/04/10 21:45:03 [error] 25#25: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET /fr HTTP/1.1", upstream: "fastcgi://192.168.80.3:9000", host: "localhost", referrer: "https://medium.com/@dam1enWeb/symfony-5-2-et-php-8-sous-docker-en-5-minutes-942ca6e94ce0"
2022/04/10 21:45:04 [error] 25#25: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET /fr HTTP/1.1", upstream: "fastcgi://192.168.80.3:9000", host: "localhost", referrer: "https://medium.com/@dam1enWeb/symfony-5-2-et-php-8-sous-docker-en-5-minutes-942ca6e94ce0"
2022/04/10 21:45:34 [error] 25#25: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET /fr HTTP/1.1", upstream: "fastcgi://192.168.80.3:9000", host: "localhost", referrer: "https://medium.com/@dam1enWeb/symfony-5-2-et-php-8-sous-docker-en-5-minutes-942ca6e94ce0"
2022/04/10 21:45:52 [error] 25#25: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET /fr HTTP/1.1", upstream: "fastcgi://192.168.80.3:9000", host: "localhost", referrer: "https://medium.com/@dam1enWeb/symfony-5-2-et-php-8-sous-docker-en-5-minutes-942ca6e94ce0"
2022/04/10 22:13:03 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.112.3:9000", host: "localhost"
2022/04/10 22:13:04 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.112.3:9000", host: "localhost"
2022/04/10 22:13:16 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.112.3:9000", host: "localhost"
2022/04/10 22:13:17 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.112.3:9000", host: "localhost"
2022/04/10 22:13:33 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.112.3:9000", host: "localhost"
2022/04/10 22:13:34 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.112.3:9000", host: "localhost"
2022/04/10 22:13:35 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.112.3:9000", host: "localhost"
2022/04/10 22:13:40 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.112.3:9000", host: "localhost"
2022/04/10 22:13:42 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.112.3:9000", host: "localhost"
